# Custom config to build without Cycles
set(WITH_CYCLES             OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_OSL        OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_EMBREE    OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_CUDA      OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_HIP       OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_LOGGING   OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_OPTIX     OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_STANDALONE OFF CACHE BOOL "" FORCE)
